spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.10.202:3300/evaluation?characterEncoding=UTF-8&serverTimezone=GMT%2B8&sslMode=DISABLED&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: nj_evaluation
    password: hkl42yOOhduXurnF
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
server:
  port: 8889
logging:
  file:
    path: C:/log/evaluation
  level:
    root: info
    com.njmetro.evaluation.mapper: info