spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.138.37:3300/evaluation?characterEncoding=UTF-8&serverTimezone=GMT%2B8&sslMode=DISABLED&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: nj_evaluation
    password: hkl42yOOhduXurnF
server:
  port: 8889
logging:
  file:
    path: d:/log/evaluation
  level:
    root: info
    com.njmetro.evaluation.mapper: debug